# Generated by Django 4.2.5 on 2023-10-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPrimaryDetails',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserFullName', models.CharField(max_length=255)),
                ('UserGender', models.CharField(max_length=255)),
                ('UserOccupation', models.CharField(max_length=255)),
                ('UserDateOfBirth', models.DateField()),
                ('UserRole', models.CharField(max_length=255)),
                ('UserMobileNum', models.CharField(max_length=255)),
                ('UserPoints', models.IntegerField()),
                ('UserImageFilename', models.ImageField(upload_to='')),
                ('UserAge', models.IntegerField()),
            ],
        ),
    ]
