# Generated by Django 4.2.5 on 2023-10-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticiansPrimaryDetails',
            fields=[
                ('PoliticianID', models.IntegerField(primary_key=True, serialize=False)),
                ('ElectionRun', models.IntegerField()),
                ('ElectionWon', models.IntegerField()),
                ('TimeLeft', models.IntegerField()),
                ('PoliticianRole', models.CharField(max_length=255)),
            ],
        ),
    ]
