# Generated by Django 4.2.5 on 2023-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_countryconstituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='politiciansprimarydetails',
            name='PoliticianName',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
