# Generated by Django 4.2.5 on 2023-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_mpelection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpelection',
            name='id',
        ),
        migrations.AddField(
            model_name='mpelection',
            name='Constituency',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpelection',
            name='ElectionStatus',
            field=models.BooleanField(primary_key=True, serialize=False),
        ),
    ]
