# Generated by Django 4.2.5 on 2023-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_mpelection_id_mpelection_constituency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpelection',
            name='ElectionStatus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mpelection',
            name='StartTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
