# Generated by Django 4.2.5 on 2023-10-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_politiciansprimarydetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprimarydetails',
            name='ForeignKey',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
