# Generated by Django 4.2.5 on 2023-10-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_usersprimarydetails_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprimarydetails',
            name='ForeignKey',
        ),
    ]
