# Generated by Django 4.2.5 on 2023-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_usersprimarydetails_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprimarydetails',
            name='UserID',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
