# Generated by Django 4.2.5 on 2023-10-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_usersprimarydetails_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpelection',
            name='Candidate2ID',
        ),
        migrations.AlterField(
            model_name='mpelection',
            name='Candidate1ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mpelection',
            name='Constituency',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='politiciansprimarydetails',
            name='PoliticianID',
            field=models.IntegerField(),
        ),
    ]
