# Generated by Django 4.2.5 on 2023-10-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_remove_politiciansprimarydetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiciansprimarydetails',
            name='PoliticianID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.usersprimarydetails'),
        ),
    ]
