# Generated by Django 4.2.5 on 2023-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_mpelection_candidate2id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpelection',
            name='CD1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpelection',
            name='CD2',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
