# Generated by Django 4.2.5 on 2023-10-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_mpelection_cd1_mpelection_cd2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpelection',
            old_name='CD1',
            new_name='Cd1',
        ),
        migrations.RenameField(
            model_name='mpelection',
            old_name='CD2',
            new_name='Cd2',
        ),
    ]
