# Generated by Django 4.2.5 on 2023-10-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_rename_cd1_mpelection_cd1_rename_cd2_mpelection_cd2'),
    ]

    operations = [
        migrations.AddField(
            model_name='politiciansprimarydetails',
            name='Pid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
