# Generated by Django 4.2.5 on 2023-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_politiciansprimarydetails_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpelection',
            name='VoteDoneList',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
