# Generated by Django 4.2.5 on 2023-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_politiciansprimarydetails_politicianrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiciansprimarydetails',
            name='PoliticianRole',
            field=models.CharField(max_length=255),
        ),
    ]
