# Generated by Django 4.2.5 on 2023-10-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_ministerprimarydetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinisterPrimaryDetails',
        ),
    ]
