# Generated by Django 4.2.5 on 2023-10-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_delete_ministerprimarydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisterPrimaryDetails',
            fields=[
                ('MinistryName', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('MinisterConstituency', models.CharField(max_length=254)),
                ('MinisterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.politiciansprimarydetails')),
            ],
        ),
    ]
