# Generated by Django 4.2.5 on 2023-10-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_alter_ministerprimarydetails_ministerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryministries',
            name='MinisterName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
