# Generated by Django 4.2.5 on 2023-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_countryministries_ministername'),
    ]

    operations = [
        migrations.AddField(
            model_name='politiciansprimarydetails',
            name='IsMinister',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
