# Generated by Django 4.2.5 on 2023-10-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_politiciansprimarydetails_isminister'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryministries',
            name='MinisterID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
