# Generated by Django 4.2.5 on 2023-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_alter_ministerprimarydetails_ministerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerprimarydetails',
            name='MinisterNumberID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
