# Generated by Django 4.2.5 on 2023-10-13 10:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_alter_mpelection_candidate1id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('NewsTitle', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('Details', tinymce.models.HTMLField()),
                ('Posting_Time', models.DateTimeField()),
                ('Channel_Name', models.CharField(max_length=500)),
                ('Reporter_Name', models.CharField(max_length=500)),
            ],
        ),
    ]
