# Generated by Django 4.2.5 on 2023-10-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='NewsNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
