# Generated by Django 4.2.5 on 2023-10-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_news_newsnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='NewsNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='NewsTitle',
            field=models.CharField(max_length=1000),
        ),
    ]
