# Generated by Django 4.2.5 on 2023-10-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_publicopinions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicopinions',
            name='OpinionID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
