# Generated by Django 4.2.5 on 2023-10-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_publicopinions_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicopinions',
            name='OpinionID',
        ),
        migrations.AlterField(
            model_name='publicopinions',
            name='Opinion',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
