# Generated by Django 4.2.5 on 2023-10-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_remove_publicopinions_opinionid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
