# Generated by Django 4.2.7 on 2023-12-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_alter_movies_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sport', models.CharField(max_length=1000)),
                ('Vanue', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
                ('SeatType', models.CharField(max_length=1000)),
                ('TicketPrice', models.IntegerField()),
            ],
        ),
    ]
