# Generated by Django 4.2.7 on 2023-12-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SportVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('Sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sport')),
            ],
        ),
        migrations.CreateModel(
            name='SportTicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameError', models.IntegerField()),
                ('SeatType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.seattype')),
            ],
        ),
        migrations.CreateModel(
            name='SportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField()),
                ('SportVenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportvenue')),
            ],
        ),
        migrations.AddField(
            model_name='seattype',
            name='SportDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sportdate'),
        ),
    ]
