# Generated by Django 4.2.7 on 2023-12-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_seattype_sport_sportvenue_sportticketprice_sportdate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeatType',
            new_name='SportSeatType',
        ),
        migrations.RenameField(
            model_name='sportticketprice',
            old_name='SeatType',
            new_name='SportSeatType',
        ),
    ]
