# Generated by Django 4.2.7 on 2023-12-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_rename_seattype_sportseattype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportticketprice',
            old_name='NameError',
            new_name='name',
        ),
    ]
