# Generated by Django 4.2.7 on 2023-12-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_rename_nameerror_sportticketprice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportdate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
