# Generated by Django 4.2.7 on 2023-12-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_alter_sportdate_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportTicketPrice',
        ),
    ]
