# Generated by Django 4.2.6 on 2023-12-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_college_honours_masters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='College',
            new_name='Collegee',
        ),
        migrations.RenameModel(
            old_name='Masters',
            new_name='Honourss',
        ),
        migrations.RenameModel(
            old_name='Honours',
            new_name='Masterss',
        ),
    ]
