# Generated by Django 4.2.6 on 2023-12-12 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_rename_college_collegee_rename_masters_honourss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=100)),
                ('user_information', models.TextField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.collegee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.subject')),
            ],
        ),
    ]
