# Generated by Django 4.2.6 on 2023-12-12 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_subject_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.collegee')),
            ],
        ),
        migrations.CreateModel(
            name='HonoursAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('honours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.honourss')),
            ],
        ),
        migrations.CreateModel(
            name='HonoursSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MastersAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('masters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.masterss')),
            ],
        ),
        migrations.CreateModel(
            name='MastersSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='CollegeSubject',
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.AddField(
            model_name='mastersadmission',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.masterssubject'),
        ),
        migrations.AddField(
            model_name='honoursadmission',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.honourssubject'),
        ),
        migrations.AddField(
            model_name='collegeadmission',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.collegesubject'),
        ),
    ]
