# Generated by Django 4.2.6 on 2023-12-13 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_collegeadmission_honoursadmission_honourssubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('school_name', models.CharField(max_length=255)),
                ('school_graduation_year', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.collegee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.collegesubject')),
            ],
        ),
        migrations.CreateModel(
            name='HonoursApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('collage_name', models.CharField(max_length=255)),
                ('collage_graduation_year', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('honours_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.honourss')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.honourssubject')),
            ],
        ),
        migrations.CreateModel(
            name='MastersApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('honours_from', models.CharField(max_length=255)),
                ('honours_graduation_year', models.DateField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('masters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.masterss')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.collegesubject')),
            ],
        ),
        migrations.RemoveField(
            model_name='honoursadmission',
            name='honours',
        ),
        migrations.RemoveField(
            model_name='honoursadmission',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='mastersadmission',
            name='masters',
        ),
        migrations.RemoveField(
            model_name='mastersadmission',
            name='subject',
        ),
        migrations.DeleteModel(
            name='CollegeAdmission',
        ),
        migrations.DeleteModel(
            name='HonoursAdmission',
        ),
        migrations.DeleteModel(
            name='MastersAdmission',
        ),
    ]
