# Generated by Django 4.2.6 on 2023-12-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_collegeapplicant_honoursapplicant_mastersapplicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='honoursapplicant',
            old_name='honours_in',
            new_name='institute_name',
        ),
        migrations.RenameField(
            model_name='mastersapplicant',
            old_name='masters',
            new_name='institute_name',
        ),
    ]
