# Generated by Django 4.2.6 on 2023-12-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_rename_honours_in_honoursapplicant_institute_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeapplicant',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='collegeapplicant',
            name='school_graduation_year',
        ),
        migrations.RemoveField(
            model_name='honoursapplicant',
            name='collage_graduation_year',
        ),
        migrations.RemoveField(
            model_name='honoursapplicant',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='mastersapplicant',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='mastersapplicant',
            name='honours_graduation_year',
        ),
    ]
