# Generated by Django 4.2.6 on 2023-12-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0063_remove_collegeapplicant_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('facility', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
