# Generated by Django 4.2.7 on 2023-12-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportTickets',
            fields=[
                ('SportName', models.CharField(max_length=500)),
                ('SportVenue', models.CharField(max_length=1000)),
                ('SportDate', models.CharField(max_length=100)),
                ('SportSeatType', models.CharField(max_length=100)),
                ('SportSeatNumber', models.CharField(max_length=500)),
                ('SportTicketPrice', models.CharField(max_length=500)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.usersprimarydetails')),
            ],
        ),
    ]
